global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'habitify_backend'
    static_configs:
      - targets: ['habitify-8qnw.onrender.com']
    metrics_path: /metrics
    scheme: https

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
